### ISSUE TITLE
pick own instances

### ISSUE THREAD

**Issue by EduardSchwarzkopf** [C3n7ral051nt4g3ncy/Masto#2]
How about I'll add a function, that can do a generic search based on the user's input?
e.g. instead of going one by one function, you can decide what instances you want to search.
Maybe also an array option with multiple instances for the same username?

**Comment by C3n7ral051nt4g3ncy** [comment]
@EduardSchwarzkopf:

- cool ideas! 
- Basically, the first function uses the Mastodon api to search for a user across all instances. If you check the [readme.md update](https://github.com/C3n7ral051nt4g3ncy/Masto#%EF%B8%8F-issues-with-not-finding-a-user), an answer was given by the Mastodon team about the api not being fully reliable.

- See also the [readme.md update](https://github.com/C3n7ral051nt4g3ncy/Masto#-tool-unsuccessful-use-cases) regarding the unsuccessful use case for the user `@sector035`, so your idea of multiple instances being searched for the same username is exactly the fix we need, and this is what @Webbreacher suggested this morning.

- For this, maybe having a `.json` file with every instance on, and searching for the user. Then we can keep working on the project in the future and to keep adding new instances to the `.json`.

**Comment by EduardSchwarzkopf** [comment]
Sounds great.
I'm going to play around with it a bit more.
Can you assign the issue to me, I'm going to make PR, later ith the changes

**Comment by rly0nheart** [comment]
Hello I made some changes to my fork of the project. I'll open a PR then you can review the changes?

**Comment by C3n7ral051nt4g3ncy** [comment]
@rly0nheart OK. thanks.

**Comment by C3n7ral051nt4g3ncy** [comment]
Hey @EduardSchwarzkopf ! I think we can now close this issue.
I added `argparse`, added an awesome `new feature` that comes in support of the Mastodon API, as suggested by @Webbreacher, and scans Masto's own server database.

Check it out!

**Comment by EduardSchwarzkopf** [comment]
Awesome and perfect timing!

**Comment by C3n7ral051nt4g3ncy** [comment]
@EduardSchwarzkopf Let me know if you feel like adding anything, also feel free to start adding more servers to the [json](https://github.com/C3n7ral051nt4g3ncy/Masto/blob/master/fediverse_instances.json)
